# Site settings
title: korbonits | Math ∩ Data
email: alex@korbonits.com
description: > # this means to ignore newlines until "baseurl:"
  Born and raised in Seattle<br>
  Currently working at Assurance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://korbonits.github.io" # the base hostname & protocol for your site
twitter_username: korbonits
github_username:  korbonits

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Exlcude certain things:
exclude: ['README.md', 'LICENSE', '_drafts']

# Google Analytics
google_analytics: UA-131731029-1
