# Site settings
title: korbonits | Math ∩ Data
email: alexkorbonits@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Born and raised in Seattle.<br>
  Currently working at Nuiku, Inc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://korbonits.github.io" # the base hostname & protocol for your site
twitter_username: korbonits
github_username:  korbonits

# Build settings
markdown: kramdown
highlighter: pygments

# Exlcude certain things:
exclude: ['README.md', 'LICENSE', '_drafts']